FROM nginx:latest

# Copiamos el contenido web personalizado
COPY index.html /usr/share/nginx/html/index.html

# Copiamos la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiamos el certificado y clave para HTTPS
COPY cert.pem /etc/ssl/certs/cert.pem
COPY key.pem /etc/ssl/private/key.pem

# Copiamos el archivo de autenticación
COPY .htpasswd /etc/nginx/.htpasswd

# Exponemos el puerto 8443 para HTTPS
EXPOSE 8443

# Arrancamos Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]

